name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  docs-link-check:
    name: Check internal links in Markdown
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Lychee link checker (offline, Markdown only)
        uses: lycheeverse/lychee-action@v1.10.0
        with:
          args: --offline --no-progress --include-fragments "./**/*.md"
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

  repo-sanity:
    name: Repo sanity
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: List files and preview README
        run: |
          echo "Files in repo:" && ls -la
          echo "\nREADME preview:" && sed -n '1,60p' README.md

  frontend-build:
    name: Frontend build (Vite/React)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json
      - name: Install deps
        working-directory: frontend
        run: npm ci
      - name: Build
        working-directory: frontend
        run: npm run build

  frontend-lint:
    name: Frontend lint (ESLint)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json
      - name: Install deps
        working-directory: frontend
        run: npm ci
      - name: Lint
        working-directory: frontend
        run: npm run lint

  backend-docker-build:
    name: Backend build (Docker/Gradle)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Docker metadata
        run: docker version && docker info
      - name: Build backend image (compiles Spring Boot)
        run: |
          docker build \
            -f backend/Dockerfile \
            -t pocketfolio-backend-ci:latest \
            backend

  backend-test:
    name: Backend tests (Gradle in Docker)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Gradle tests inside container
        run: |
          docker run --rm \
            -v "$PWD/backend":/home/gradle/project \
            -w /home/gradle/project \
            gradle:8.8.0-jdk21 \
            gradle test
